### ISSUE TITLE
avalanche.CChain().keyChain().hasKey(address) always returns false

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchejs#377] opened 2021-10-07 06:22 UTC
Hello Team
I am validating the address, but it always returns false. 

  const avalanchejs = require("avalanche");
  const avalanche = new avalanchejs.Avalanche("localhost", 9650, "http", "1");
  **let address = avalanche.CChain().keyChain().makeKey().getAddressString();**
  **address = "2q9e4r6Mu3U68nU1fYjgbR6JvwrRx36CohpAX5UQxse55x1Q5-custom1e7y32y96jwrde8tae4d6ekjmwq55as695ek9n2"**
  let isValid = avalanche.CChain().keyChain().hasKey(address);

 o/p isValid is false.

**Comment by paOol** [comment] 2021-10-18 19:09
I'm not sure what you're trying to do with the boolean value, but your address is incorrect.

The response from `getAddressString()` should look something like `C-local1w2x45geasjuyn0jzjkr08e5qtdwqczzvr08gpp` or `C-avax1rxz2d9809y7pgw7nsdymel426w0qdw3mrk6vlp`

Here is a code sample of how I got the address string

```
import { Avalanche } from "../../src"
import { EVMAPI, KeyChain } from "../../src/apis/evm"

const ip: string = "localhost"
const port: number = 9650
const protocol: string = "http"
const networkID: number = 1
const avalanche: Avalanche = new Avalanche(ip, port, protocol, networkID)
const cchain: EVMAPI = avalanche.CChain()

const main = async (): Promise<any> => {
  const keychain: KeyChain = cchain.keyChain()
  const address: any = keychain.makeKey().getAddressString()

  console.log("address", address)
}

main()

```

closing this issue because it cannot be reproduced.

**Closed as completed by paOol** 2021-10-18 19:09 UTC
