### ISSUE TITLE
Custody Verification

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanchejs#295] opened 2021-08-13 11:08 UTC
Hi Team
i am using avalanche-rosetta node, now i like to implement custody verification.
can i perform custody verification on rosetta server? if yes, please provide document/example.

Thanks

**Comment by cgcardona** [comment] 2021-08-17 14:56
What do you mean by custody verification?

**Comment by paOol** [comment] 2021-08-18 06:25
duplicate of https://github.com/ava-labs/avalanche-rosetta/issues/26
and outside of the scope of this repo.

closing.

**Closed by paOol** 2021-08-18 06:25 UTC
